import * as dashboardConstants from "@/app/dashboard/dashboard-services/dashboard-constants";

const {
  ALL_FEEDS_NODE_KEY,
  DASHBOARD_ARTICLE_FILTER_STORAGE_KEY,
  DASHBOARD_ARTICLES_PER_PAGE_STORAGE_KEY,
  DASHBOARD_EVENTS,
  DASHBOARD_SELECTED_CATEGORY_STORAGE_KEY,
  MOBILE_INVERTED_SCROLL_STORAGE_KEY,
  MOBILE_UI_GROUPED_LAYOUT_STORAGE_KEY,
  SETTINGS_PANEL_TAB_STORAGE_KEY,
} = dashboardConstants;

export {
  ALL_FEEDS_NODE_KEY,
  DASHBOARD_ARTICLE_FILTER_STORAGE_KEY,
  DASHBOARD_ARTICLES_PER_PAGE_STORAGE_KEY,
  DASHBOARD_EVENTS,
  DASHBOARD_SELECTED_CATEGORY_STORAGE_KEY,
  MOBILE_INVERTED_SCROLL_STORAGE_KEY,
  MOBILE_UI_GROUPED_LAYOUT_STORAGE_KEY,
  SETTINGS_PANEL_TAB_STORAGE_KEY,
};
export type { BackgroundMode } from "@/app/dashboard/dashboard-services/dashboard-constants";
